#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RxTap.Resource", IsApplication=true)]

namespace RxTap
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090001
			public const int dispenseItems = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int instructionItems = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int strengthItems = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int clrAcceptedGreen = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int clrBackground = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int clrBackgroundDark = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int clrBlack = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int clrDarkGrey = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int clrLightGrey = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int clrRejectedRed = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int clrWhite = 2131165188;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int cardview_compat_inset_shadow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int cardview_default_elevation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int cardview_default_radius = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addPrescriptionButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int imgAccept = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int imgAdd = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int imgDefaultPill = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int imgReject = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int RxTap = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int RxTap_title = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int RxTap_title_small = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int title_background = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int addDataBtn = 2131034123;
			
			// aapt resource value: 0x7f050068
			public const int addDoseBtn = 2131034216;
			
			// aapt resource value: 0x7f05005c
			public const int addNewMedBtn = 2131034204;
			
			// aapt resource value: 0x7f050062
			public const int btnHistory = 2131034210;
			
			// aapt resource value: 0x7f050010
			public const int buttonReturnToHistory = 2131034128;
			
			// aapt resource value: 0x7f05006a
			public const int buttonReturnToMain = 2131034218;
			
			// aapt resource value: 0x7f05002a
			public const int buttonToggleNote = 2131034154;
			
			// aapt resource value: 0x7f05005d
			public const int cancelNewMedBtn = 2131034205;
			
			// aapt resource value: 0x7f05000d
			public const int clearDataBtn = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int clearDosagebtn = 2131034126;
			
			// aapt resource value: 0x7f050069
			public const int deletePrescBtn = 2131034217;
			
			// aapt resource value: 0x7f05006d
			public const int editText1 = 2131034221;
			
			// aapt resource value: 0x7f05005f
			public const int horLayoutUsrNm = 2131034207;
			
			// aapt resource value: 0x7f050004
			public const int imageView1 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int imgLogo = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050064
			public const int linLayoutCard = 2131034212;
			
			// aapt resource value: 0x7f050016
			public const int linearAddMedicationInfo = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout1 = 2131034117;
			
			// aapt resource value: 0x7f050030
			public const int linearLayout10 = 2131034160;
			
			// aapt resource value: 0x7f050033
			public const int linearLayout11 = 2131034163;
			
			// aapt resource value: 0x7f050039
			public const int linearLayout12 = 2131034169;
			
			// aapt resource value: 0x7f05003c
			public const int linearLayout13 = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int linearLayout14 = 2131034175;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout2 = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout3 = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int linearLayout4 = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int linearLayout5 = 2131034139;
			
			// aapt resource value: 0x7f050020
			public const int linearLayout6 = 2131034144;
			
			// aapt resource value: 0x7f050024
			public const int linearLayout7 = 2131034148;
			
			// aapt resource value: 0x7f050028
			public const int linearLayout8 = 2131034152;
			
			// aapt resource value: 0x7f05002d
			public const int linearLayout9 = 2131034157;
			
			// aapt resource value: 0x7f05002b
			public const int linearMedicationInfo = 2131034155;
			
			// aapt resource value: 0x7f050043
			public const int linearUserDoses = 2131034179;
			
			// aapt resource value: 0x7f05000c
			public const int loadDataBtn = 2131034124;
			
			// aapt resource value: 0x7f05006f
			public const int localDataBtn = 2131034223;
			
			// aapt resource value: 0x7f05000a
			public const int rawDataInput = 2131034122;
			
			// aapt resource value: 0x7f05006b
			public const int recyclerMedList = 2131034219;
			
			// aapt resource value: 0x7f050061
			public const int relLayoutButton = 2131034209;
			
			// aapt resource value: 0x7f050012
			public const int relLayoutTitle = 2131034130;
			
			// aapt resource value: 0x7f05006e
			public const int saveBtn = 2131034222;
			
			// aapt resource value: 0x7f050011
			public const int scrollView1 = 2131034129;
			
			// aapt resource value: 0x7f050027
			public const int spinnerAddDispensed = 2131034151;
			
			// aapt resource value: 0x7f050037
			public const int spinnerAddInstruction = 2131034167;
			
			// aapt resource value: 0x7f050023
			public const int spinnerAddStrength = 2131034147;
			
			// aapt resource value: 0x7f050070
			public const int tapNoBtn = 2131034224;
			
			// aapt resource value: 0x7f050009
			public const int tapOkBtn = 2131034121;
			
			// aapt resource value: 0x7f050071
			public const int tapOkBtnBad = 2131034225;
			
			// aapt resource value: 0x7f05000f
			public const int testDataDisplay = 2131034127;
			
			// aapt resource value: 0x7f05001e
			public const int textAddBrand = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int textAddBrandEdit = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int textAddDIN = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int textAddDINEdit = 2131034138;
			
			// aapt resource value: 0x7f050040
			public const int textAddDateFilled = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int textAddDateFilledEdit = 2131034177;
			
			// aapt resource value: 0x7f050031
			public const int textAddDirectionEnd = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int textAddDirectionEndEdit = 2131034162;
			
			// aapt resource value: 0x7f050034
			public const int textAddDirectionInstructions = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int textAddDirectionInstructionsEdit = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int textAddDirectionInstructionsTimes = 2131034166;
			
			// aapt resource value: 0x7f05002e
			public const int textAddDirectionStart = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int textAddDirectionStartEdit = 2131034159;
			
			// aapt resource value: 0x7f050025
			public const int textAddDispensed = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int textAddDispensedEdit = 2131034150;
			
			// aapt resource value: 0x7f05001c
			public const int textAddManufacturer = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int textAddManufacturerEdit = 2131034141;
			
			// aapt resource value: 0x7f050014
			public const int textAddMedName = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int textAddMedNameEdit = 2131034133;
			
			// aapt resource value: 0x7f050029
			public const int textAddNotes = 2131034153;
			
			// aapt resource value: 0x7f050046
			public const int textAddPharmacyAddress = 2131034182;
			
			// aapt resource value: 0x7f050045
			public const int textAddPharmacyName = 2131034181;
			
			// aapt resource value: 0x7f050047
			public const int textAddPharmacyPhone = 2131034183;
			
			// aapt resource value: 0x7f050042
			public const int textAddPhysician = 2131034178;
			
			// aapt resource value: 0x7f05003a
			public const int textAddRX = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int textAddRXEdit = 2131034171;
			
			// aapt resource value: 0x7f05003d
			public const int textAddRefills = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int textAddRefillsEdit = 2131034174;
			
			// aapt resource value: 0x7f05002c
			public const int textAddStaticDosage = 2131034156;
			
			// aapt resource value: 0x7f050017
			public const int textAddStaticMedInfo = 2131034135;
			
			// aapt resource value: 0x7f050044
			public const int textAddStaticPharmacy = 2131034180;
			
			// aapt resource value: 0x7f050038
			public const int textAddStaticPrescriptionInfo = 2131034168;
			
			// aapt resource value: 0x7f050021
			public const int textAddStrength = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int textAddStrengthEdit = 2131034146;
			
			// aapt resource value: 0x7f050048
			public const int textBrand = 2131034184;
			
			// aapt resource value: 0x7f05004a
			public const int textDIN = 2131034186;
			
			// aapt resource value: 0x7f050056
			public const int textDateFilled = 2131034198;
			
			// aapt resource value: 0x7f050052
			public const int textDirectionInstructions = 2131034194;
			
			// aapt resource value: 0x7f050067
			public const int textDirectionTimePreference = 2131034215;
			
			// aapt resource value: 0x7f050051
			public const int textDirectionWindow = 2131034193;
			
			// aapt resource value: 0x7f05004e
			public const int textDispensed = 2131034190;
			
			// aapt resource value: 0x7f05004b
			public const int textManufacturer = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int textMedName = 2131034188;
			
			// aapt resource value: 0x7f05004f
			public const int textNotes = 2131034191;
			
			// aapt resource value: 0x7f05005a
			public const int textPharmacyAddress = 2131034202;
			
			// aapt resource value: 0x7f050059
			public const int textPharmacyName = 2131034201;
			
			// aapt resource value: 0x7f05005b
			public const int textPharmacyPhone = 2131034203;
			
			// aapt resource value: 0x7f050057
			public const int textPhysician = 2131034199;
			
			// aapt resource value: 0x7f050054
			public const int textRX = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int textRefills = 2131034197;
			
			// aapt resource value: 0x7f050050
			public const int textStaticDosage = 2131034192;
			
			// aapt resource value: 0x7f050049
			public const int textStaticMedInfo = 2131034185;
			
			// aapt resource value: 0x7f050058
			public const int textStaticPharmacy = 2131034200;
			
			// aapt resource value: 0x7f050053
			public const int textStaticPrescriptionInfo = 2131034195;
			
			// aapt resource value: 0x7f05004d
			public const int textStrength = 2131034189;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textView3 = 2131034119;
			
			// aapt resource value: 0x7f050066
			public const int txtDosage = 2131034214;
			
			// aapt resource value: 0x7f050065
			public const int txtMedTitle = 2131034213;
			
			// aapt resource value: 0x7f050060
			public const int txtUserName = 2131034208;
			
			// aapt resource value: 0x7f050063
			public const int userSettingBtn = 2131034211;
			
			// aapt resource value: 0x7f05006c
			public const int userText = 2131034220;
			
			// aapt resource value: 0x7f050001
			public const int vertLayoutRoot = 2131034113;
			
			// aapt resource value: 0x7f05005e
			public const int vertLayoutTitle = 2131034206;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int tapViewNew = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int testAddLocalData = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int viewAddMed = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int viewAddNewMedDtls = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int viewMain = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int viewMedCard = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int viewMedDtls = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int viewMedList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int viewSettings = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int viewTap = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int viewTapBad = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Base_CardView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button_text = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
