using System;
using System.Collections.Generic;

namespace RxTap
{
    //units for medication strength, dispensed amount, and dosage frequency
    public static class UNITS
    {
        public static string MG { get { return "mg"; } }
        public static string G { get { return "g"; } }
        public static string MCG { get { return "mcg"; } }
        public static string ML { get { return "ml"; } }
        public static string CAPSULE { get { return "cap"; } }
        public static string TABLET { get { return "tab"; } }
        public static string PILL { get { return "pill"; } }
        public static string DAY { get { return "day"; } }
        public static string WEEK { get { return "week"; } }
        public static string MONTH { get { return "month"; } }
    }

    //Contains data about a user's taken dosage from an existing prescription
    public class TakenDosage
    {
        private int _dosageID;          //auto-generated by the app whenever new TakenDosage is created
        private int _rxID;              //id of the prescription the dosage was taken from
        private DateTime _dateTaken;    //date the dosage was taken (day/month/year)
        private DateTime _timeTaken;    //time the dosage was taken (hours:minutes)

        public int DosageID
        {
            get { return _dosageID; }
            set { _dosageID = value; }
        }
        
        public int RXID
        {
            get { return _rxID; }
            set { _rxID = value; }
        }
        
        public DateTime DateTaken
        {
            get { return _dateTaken; }
            set { _dateTaken = value; }
        }
        
        public DateTime TimeTaken
        {
            get { return _timeTaken; }
            set { _timeTaken = value; }
        }
        
        public TakenDosage(int dosageID, int rxID, DateTime dateTaken, DateTime timeTaken)
        {
            _dosageID = dosageID;
            _rxID = rxID;
            _dateTaken = dateTaken;
            _timeTaken = timeTaken;
        }
    }

    //Contains all data for a type and brand of medication
    public class Medication
    {
        private int _DIN;               //8-digit Drug Identification Number, assigned by Health Canada
        private String _manufacturer;   //company that manufactured drug (eg. PFIZER)
        private String _brandName;      //brand name of the drug (eg. ADVIL)
        private String _genericName;    //generic name of drug (eg. IBUPROFEN)
        private float _strengthQty;     //quantity of strength of the drug (eg. 1000)
        private String _strengthUnit;   //unit of strength of the drug (eg. MG)
        private int _dispensedQty;      //quantity of drug that is dispensed (eg. 50)
        private String _dispensedUnit;  //unit of drug that is dispensed (eg. TABLETS)
        private List<String> _additionalNotes;  //additional notes (eg. TAKE WITH FOOD)
        
        public int DIN
        {
            get { return _DIN; }
            set { _DIN = value; }
        }
        
        public String Manufacturer
        {
            get { return _manufacturer; }
            set { _manufacturer = value; }
        }
        
        public String BrandName
        {
            get { return _brandName; }
            set { _brandName = value; }
        }
        
        public String GenericName
        {
            get { return _genericName; }
            set { _genericName = value; }
        }
        
        public float StrengthQty
        {
            get { return _strengthQty; }
            set { _strengthQty = value; }
        }
        
        public String StrengthUnit
        {
            get { return _strengthUnit; }
            set { _strengthUnit = value; }
        }
        
        public int DispensedQty
        {
            get { return _dispensedQty; }
            set { _dispensedQty = value; }
        }
        
        public String DispensedUnit
        {
            get { return _dispensedUnit; }
            set { _dispensedUnit = value; }
        }
        
        public List<String> AdditionalNotes
        {
            get { return _additionalNotes; }
            set { _additionalNotes = value; }
        }
        
        public Medication(int DIN, String manufacturer, String brandName, String genericName, float strengthQty, String strengthUnit, int dispensedQty, String dispensedUnit, List<String> additionalNotes = null)
        {
            _DIN = DIN;
            _manufacturer = manufacturer;
            _brandName = brandName;
            _genericName = genericName;
            _strengthQty = strengthQty;
            _strengthUnit = strengthUnit;
            _dispensedQty = dispensedQty;
            _dispensedUnit = dispensedUnit;
            _additionalNotes = additionalNotes;

            if (_additionalNotes == null)
                _additionalNotes = new List<String>();
        }
    }

    //Contains all data about the pharmacy that filled out the prescription
    public class Pharmacy
    {
        private String _name;           //name of the pharmacy
        private String _address;        //address of the pharmacy
        private String _phoneNumber;    //phone number of pharmacy
        
        public String Name
        {
            get { return _name; }
            set { _name = value; }
        }

        public String Address
        {
            get { return _address; }
            set { _address = value; }
        }
        
        public String PhoneNumber
        {
            get { return _phoneNumber; }
            set { _phoneNumber = value; }
        }

        public Pharmacy(String name, String address, String phoneNumber)
        {
            _name = name;
            _address = address;
            _phoneNumber = phoneNumber;
        }
    }

    //Contains all data on a physician who prescribed medication
    public class Physician
    {
        private String _firstName;  //physician's first name
        private String _lastName;   //physician's last name
        
        public String FirstName
        {
            get { return _firstName; }
            set { _firstName = value; }
        }

        public String LastName
        {
            get { return _lastName; }
            set { _lastName = value; }
        }
        
        public Physician(String firstName,String lastName)
        {
            _firstName = firstName;
            _lastName = lastName;
        }
    }

    //Contains all data on directions for taking a prescription
    public class Direction
    {
        private DateTime _startDate;        //start date of prescription (set to current day when adding new prescription by default)
        private DateTime _endDate;          //estimated end date of prescription (calculated based on dispensed qty, dosage frequency and start date)
        private int _frequencyQty;          //quantity of the frequency the prescription should be taken (eg. 2)
        private String _frequencyUnit;      //unit of the frequency the prescription should be taken (eg. day)
        private List<DateTime> _preferredTimes; //list of times user can set to be notified to take prescription
        
        public DateTime StartDate
        {
            get { return _startDate; }
            set { _startDate = value; }
        }
        
        public DateTime EndDate
        {
            get { return _endDate; }
            set { _endDate = value; }
        }

        public int FrequencyQty
        {
            get { return _frequencyQty; }
            set { _frequencyQty = value; }
        }

        public String FrequencyUnit
        {
            get { return _frequencyUnit; }
            set { _frequencyUnit = value; }
        }
        
        public List<DateTime> PreferredTimes
            {
            get { return _preferredTimes; }
            set { _preferredTimes = value; }
        }

        public Direction(int dispensedQty, int frequencyQty, String frequencyUnit, List<DateTime> preferredTimes = null)
        {
            _startDate = DateTime.Now;
            _endDate = CalculateEndDate(dispensedQty, frequencyQty, frequencyUnit);
            _frequencyQty = frequencyQty;
            _frequencyUnit = frequencyUnit;
            _preferredTimes = preferredTimes;

            if (_preferredTimes == null)
                _preferredTimes = new List<DateTime>();

        }

        private DateTime CalculateEndDate(int dispensedQty, int freqQty, String freqUnit)
        {

            double numberOfDays = Math.Ceiling((double)(dispensedQty / freqQty));

            if (freqUnit.ToLower().Equals(UNITS.WEEK))
            {
                numberOfDays *= 7;
            }
            else if (freqUnit.ToLower().Equals(UNITS.MONTH))
            {
                numberOfDays *= 30;
            }

            return _startDate.AddDays(numberOfDays);
        }
    }

    //Contains all data for a user's prescription
    public class Prescription
    {
        private Pharmacy _pharmacy;     //pharmacy that prepared the prescription
        private Physician _physician;   //physician who prescribed the medication
        private int _rxID;              //unique prescription ID issued by the pharmacy
        private int _refills;           //number of refills user has left for this prescription
        private DateTime _dateFilled;   //date that prescription was filled by pharmacy
        private String _patientName;    //name of patient the drug is prescribed for (does not have to equal the username)
        private Medication _medication; //medication that is being prescribed
        private Direction _direction;   //directions for taking medication
        
        public Pharmacy Pharmacy
        {
            get { return _pharmacy; }
            set { _pharmacy = value; }
        }

        public Physician Physician
        {
            get { return _physician; }
            set { _physician = value; }
        }

        public int RXID
        {
            get { return _rxID; }
            set { _rxID = value; }
        }

        public int Refills
        {
            get { return _refills; }
            set { _refills = value; }
        }

        public DateTime DateFilled
        {
            get { return _dateFilled; }
            set { _dateFilled = value; }
        }

        public String PatientName
        {
            get { return _patientName; }
            set { _patientName = value; }
        }

        public Medication Medication
        {
            get { return _medication; }
            set { _medication = value; }
        }

        public Direction Direction
        {
            get { return _direction; }
            set { _direction = value; }
        }

        public Prescription(Pharmacy pharmacy, Physician physician, int rxID, int refills, DateTime dateFilled, String patientName, Medication medication, int frequencyQty, String frequencyUnit, List<DateTime> preferredTimes = null)
        {
            _pharmacy = pharmacy;
            _physician = physician;
            _rxID = rxID;
            _refills = refills;
            _dateFilled = dateFilled;
            _patientName = patientName;
            _medication = medication;
            _direction = new Direction(_medication.DispensedQty, frequencyQty, frequencyUnit, preferredTimes);
        }
    }

    //Contains all user data
    public class User
    {
        private String _username;                   //username
        private List<Prescription> _prescriptions;  //list of all prescriptions user owns
        private List<TakenDosage> _dosageLog;       //list of all dosages user has taken
        
        public String Username
        {
            get { return _username; }
            set { _username = value; }
        }

        public List<Prescription> Prescriptions
        {
            get { return _prescriptions; }
            set { _prescriptions = value; }
        }

        public List<TakenDosage> DosageLog
        {
            get { return _dosageLog; }
            set { _dosageLog = value; }
        }

        public User(String username, List<Prescription> prescriptions, List<TakenDosage> dosageLog)
        {
            _username = username;
            _prescriptions = prescriptions;
            _dosageLog = dosageLog;
        }

        //Constructor if you only have the name of the User
        public User(String username)
        {
            _username = username;
        }
    }

}
